@echo off
echo Adding updates to Git...
git add .
echo Committing changes...
git commit -m "style: implement DarkVector Premium design updates"
echo Pushing to GitHub (this will trigger a new Vercel deployment)...
git push origin master
echo.
echo Trying direct Vercel CLI deployment as backup...
cmd /c npx vercel --prod --yes
echo.
echo Done! Your updates should now be live on Vercel.
pause
